### ISSUE TITLE
Simple example with prediction

### ISSUE THREAD

**Issue by gdalle** [rikhuijzer/SIRUS.jl#49]
The tutorial is extremely detailed, but it benchmarks a handful of approaches before even showing how to use the rule-based classifier. Maybe a dead simple example of fit-predict-evaluate would belong on the front page of the docs + in the paper, for those unfamiliar with the MLJ framework

https://github.com/openjournals/joss-reviews/issues/5786

**Comment by rikhuijzer** [comment]
This is a nice suggestion. I've added one at https://sirus.jl.huijzer.xyz/dev/basic-example/. I'll also add this to the paper. @gdalle, can you close this issue if you find the example sufficiently clear? I'm adding the example also to the paper and will request another PDF generate once I'm done with updating the paper.

**Comment by gdalle** [comment]
yes the example is good!
