### ISSUE TITLE
State of the field is missing

### ISSUE THREAD

**Issue by gdalle** [rikhuijzer/SIRUS.jl#52]
While the purpose of the package is clear (reimplementing a R/C++ code), I think it would benefit from a broader perspective on the state of ML and interpretability in Julia.
For instance explain what MLJ is, whether there are concurrent frameworks, and which packages offer interpretability tools (even based on black box models).

https://github.com/openjournals/joss-reviews/issues/5786

**Comment by rikhuijzer** [comment]
This was indeed a big issue. We had failed to mention many packages. Thank you for reporting it and providing some suggestions. In the latest PDF version in the REVIEW issue, we have tried to find a balance between your suggestions here and the original checklist item in the JOSS review checklist. Can you check whether the current PDF version has solved this issue?
