### ISSUE TITLE
Last details in JOSS paper

### ISSUE THREAD

**Issue by gdalle** [rikhuijzer/SIRUS.jl#60]
L31: "perform poor" => perform poorly
L80: "will most likely survive" => is more likely to survive (the proba from the first rule is not > 0.5)
L136: repetition of "models"

Table 1: why 2 columns for XGBoost and SIRUS?

https://github.com/openjournals/joss-reviews/issues/5786

**Comment by rikhuijzer** [comment]
Thank you, Guillaume. Very well spotted. My supervisor and I both missed these.

> Table 1: why 2 columns for XGBoost and SIRUS?
